### ISSUE TITLE
Missing Agile logo for init

### ISSUE THREAD

**Issue by mtb-za** [agile-geoscience/kosu#16]
Getting a FileNotFoundError when running `kosu init` in a new folder:
```FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mtb\\Miniconda3\\envs\\kosu\\Lib\\site-packages\\kosu\\include\\agile_logo.png'```

Should be an easy fix, just not sure which one you want.

This might be another thing that should be optional or changeable easily?

**Comment by kwinkunks** [comment]
Turns out it should have been looking for `example.png`, which is present. Removing `agile_logo.png` again.
