### ISSUE TITLE
Use color in terminal messages

### ISSUE THREAD

**Issue by kwinkunks** [agile-geoscience/kosu#7]
Apply styling by replacing calls to `echo` with `secho`, basically.

**Comment by RishiKumarRay** [comment]
Do we have to just replace echo with secho everywhere it is present?

**Comment by kwinkunks** [comment]
Fixed by f1c598d94a2dc61acfaa166ba26c6769dae5eccf - thank you @Arunodhai 

Thank you for asking, @RishiKumarRay but it's been addressed.

**Comment by RishiKumarRay** [comment]
@kwinkunks can you open up a easy issue for me or whenever you get any please let me know, Thanks

**Comment by kwinkunks** [comment]
I'll check and tag more 'good first issues' when I can. Thanks Rishi!

**Comment by Arunodhai** [comment]
> Fixed by [f1c598d](https://github.com/agile-geoscience/kosu/commit/f1c598d94a2dc61acfaa166ba26c6769dae5eccf) - thank you @Arunodhai
> 
> Thank you for asking, @RishiKumarRay but it's been addressed.

Always happy to help😇.
